### ISSUE TITLE
po_pagination_issue

### ISSUE THREAD

**Issue by idontwindows** [dostonelab2/faims#24]
PO report not overflowing to create new page when details is too long.

**Comment by ronnelg10** [comment]
paging issue still exist

e.g.
- PO-23-05-1129 - blank entries on 1st page
- PO-23-07-1196 - 1st item of each page overlaps on header

**Comment by idontwindows** [comment]
Pushed new update please check for evaluation...

**Comment by ronnelg10** [comment]
> Pushed new update please check for evaluation...

Please push update on staging server..

**Comment by idontwindows** [comment]
Noted! Already created a pull request on staging server.

**Comment by ronnelg10** [comment]
Will close the issue now. Update may now be deployed to production server
